name: Backend Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Zip source code
        run: |
          zip -r backend.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: "hannah-backend-bucket"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "."
          DEST_DIR: "backend"

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name backend_app \
            --deployment-group-name backend_app_deploy_group \
            --s3-location bucket=hannah-backend-bucket,key=backend/backend.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "GitHub Actions 배포"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
